apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebari-operator-system

resources:
  - https://raw.githubusercontent.com/nebari-dev/nebari-operator/main/dist/install.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nebari-operator-controller-manager
