apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebari-operator-system

resources:
  - https://github.com/nebari-dev/nebari-operator.git/config/default?ref=v0.1.0-alpha.2

images:
  - name: quay.io/nebari/nebari-operator
    newTag: 0.1.0-alpha.2

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nebari-operator-controller-manager
