apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebari-operator-system

resources:
  - https://github.com/nebari-dev/nebari-operator.git/config/default?ref=feature/landing-page-service-discovery

images:
  - name: quay.io/nebari/nebari-operator
    newTag: feature-landing-page-service-discovery

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nebari-operator-controller-manager
