apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebari-operator-system

resources:
  - https://github.com/nebari-dev/nebari-operator/releases/download/v0.1.0-alpha.1/install.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: nebari-operator-controller-manager
