project_name: my-nebari-azure
provider: azure
domain: nebari.example.com

azure:
  region: eastus
  kubernetes_version: "1.28"
  storage_account_postfix: "nebari"
  resource_group_name: "nebari-resources"
  private_cluster_enabled: false

  node_groups:
    general:
      instance: Standard_D8_v3
      min_nodes: 1
      max_nodes: 1

    user:
      instance: Standard_D4_v3
      min_nodes: 0
      max_nodes: 5

    worker:
      instance: Standard_D4_v3
      min_nodes: 0
      max_nodes: 5

  tags:
    Environment: development
    Project: nebari
