project_name: my-nebari-gcp
provider: gcp
domain: nebari.example.com

google_cloud_platform:
  project: my-gcp-project-id
  region: us-central1
  kubernetes_version: "1.28"
  availability_zones:
    - us-central1-a
    - us-central1-b
  release_channel: "REGULAR"
  networking_mode: "ROUTE"
  network: "default"

  node_groups:
    general:
      instance: e2-standard-8
      min_nodes: 1
      max_nodes: 1

    user:
      instance: e2-standard-4
      min_nodes: 0
      max_nodes: 5

    worker:
      instance: e2-standard-4
      min_nodes: 0
      max_nodes: 5

  tags:
    - development
    - nebari
