project_name: my-nebari-local
provider: local
domain: nebari.local
certificate:
  type: selfsigned
local:
  kube_context: "kind-nebari-local"
  node_selectors:
    general:
      kubernetes.io/os: linux
    user:
      kubernetes.io/os: linux
    worker:
      kubernetes.io/os: linux
