apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: nebari-infrastructure-core
spec:
  acme:
    email: {{ .ACMEEmail }}
    server: {{ .ACMEServer }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: nebari-gateway
                namespace: envoy-gateway-system
                kind: Gateway
